### ISSUE TITLE
cant run terrform apply get below error

### ISSUE THREAD

**Issue by germeister2019** [vinycoolguy2015/awslambda#1]
Error: error creating Backup Selection: InvalidParameterValueException: IAM Role arn:aws:iam::674762530604:role/AWSBackupServiceRole is not authorized to call tag:GetResources
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "c5878013-5c40-4b99-ba1e-094b87182650"
│   },
│   Code_: "ERROR_3018",
│   Context: "arn:aws:iam::674762530604:role/AWSBackupServiceRole",
│   Message_: "IAM Role arn:aws:iam::674762530604:role/AWSBackupServiceRole is not authorized to call tag:GetResources"
│ }
│
│   with module.backup.aws_backup_selection.backup-selection,
│   on backup_module\backup.tf line 43, in resource "aws_backup_selection" "backup-selection":
│   43: resource "aws_backup_selection" "backup-selection" {
│
╵
╷
│ Error: Error putting IAM role policy terraform-20221209162137272900000003: LimitExceeded: Maximum policy size of 10240 bytes exceeded for role AWSBackupServiceRole
│       status code: 409, request id: 0d19e64a-8e58-4d0c-8f56-48341d329e29
│
│   with module.backup.aws_iam_role_policy.backup-service-aws-backup-role-policy,
│   on backup_module\iam.tf line 42, in resource "aws_iam_role_policy" "backup-service-aws-backup-role-policy":
│   42: resource "aws_iam_role_policy" "backup-service-aws-backup-role-policy" {

**Comment by vinycoolguy2015** [comment]
Did you add any permissions because I tried terraform_aws_backup code just now and it is working fine.
